/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.units;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Length Conversion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.group32.units.units.LengthConversion#getLengthValue <em>Length Value</em>}</li>
 *   <li>{@link uk.ac.kcl.group32.units.units.LengthConversion#getInitialLength <em>Initial Length</em>}</li>
 *   <li>{@link uk.ac.kcl.group32.units.units.LengthConversion#getConvertedLength <em>Converted Length</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.group32.units.units.UnitsPackage#getLengthConversion()
 * @model
 * @generated
 */
public interface LengthConversion extends Statements
{
  /**
   * Returns the value of the '<em><b>Length Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length Value</em>' containment reference.
   * @see #setLengthValue(IntExpression)
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getLengthConversion_LengthValue()
   * @model containment="true"
   * @generated
   */
  IntExpression getLengthValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.group32.units.units.LengthConversion#getLengthValue <em>Length Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length Value</em>' containment reference.
   * @see #getLengthValue()
   * @generated
   */
  void setLengthValue(IntExpression value);

  /**
   * Returns the value of the '<em><b>Initial Length</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.group32.units.units.LengthUnits}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Length</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.LengthUnits
   * @see #setInitialLength(LengthUnits)
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getLengthConversion_InitialLength()
   * @model
   * @generated
   */
  LengthUnits getInitialLength();

  /**
   * Sets the value of the '{@link uk.ac.kcl.group32.units.units.LengthConversion#getInitialLength <em>Initial Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Length</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.LengthUnits
   * @see #getInitialLength()
   * @generated
   */
  void setInitialLength(LengthUnits value);

  /**
   * Returns the value of the '<em><b>Converted Length</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.group32.units.units.LengthUnits}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Converted Length</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.LengthUnits
   * @see #setConvertedLength(LengthUnits)
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getLengthConversion_ConvertedLength()
   * @model
   * @generated
   */
  LengthUnits getConvertedLength();

  /**
   * Sets the value of the '{@link uk.ac.kcl.group32.units.units.LengthConversion#getConvertedLength <em>Converted Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Converted Length</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.LengthUnits
   * @see #getConvertedLength()
   * @generated
   */
  void setConvertedLength(LengthUnits value);

} // LengthConversion
