/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.units;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mass Conversion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.group32.units.units.MassConversion#getMassValue <em>Mass Value</em>}</li>
 *   <li>{@link uk.ac.kcl.group32.units.units.MassConversion#getInitialMassValue <em>Initial Mass Value</em>}</li>
 *   <li>{@link uk.ac.kcl.group32.units.units.MassConversion#getConvertedMassValue <em>Converted Mass Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.group32.units.units.UnitsPackage#getMassConversion()
 * @model
 * @generated
 */
public interface MassConversion extends Statements
{
  /**
   * Returns the value of the '<em><b>Mass Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mass Value</em>' containment reference.
   * @see #setMassValue(IntExpression)
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getMassConversion_MassValue()
   * @model containment="true"
   * @generated
   */
  IntExpression getMassValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.group32.units.units.MassConversion#getMassValue <em>Mass Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mass Value</em>' containment reference.
   * @see #getMassValue()
   * @generated
   */
  void setMassValue(IntExpression value);

  /**
   * Returns the value of the '<em><b>Initial Mass Value</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.group32.units.units.MassUnits}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Mass Value</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.MassUnits
   * @see #setInitialMassValue(MassUnits)
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getMassConversion_InitialMassValue()
   * @model
   * @generated
   */
  MassUnits getInitialMassValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.group32.units.units.MassConversion#getInitialMassValue <em>Initial Mass Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Mass Value</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.MassUnits
   * @see #getInitialMassValue()
   * @generated
   */
  void setInitialMassValue(MassUnits value);

  /**
   * Returns the value of the '<em><b>Converted Mass Value</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.group32.units.units.MassUnits}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Converted Mass Value</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.MassUnits
   * @see #setConvertedMassValue(MassUnits)
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getMassConversion_ConvertedMassValue()
   * @model
   * @generated
   */
  MassUnits getConvertedMassValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.group32.units.units.MassConversion#getConvertedMassValue <em>Converted Mass Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Converted Mass Value</em>' attribute.
   * @see uk.ac.kcl.group32.units.units.MassUnits
   * @see #getConvertedMassValue()
   * @generated
   */
  void setConvertedMassValue(MassUnits value);

} // MassConversion
