/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.units;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Units</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.group32.units.units.Units#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.group32.units.units.UnitsPackage#getUnits()
 * @model
 * @generated
 */
public interface Units extends EObject
{
  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.group32.units.units.Statements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference list.
   * @see uk.ac.kcl.group32.units.units.UnitsPackage#getUnits_Statement()
   * @model containment="true"
   * @generated
   */
  EList<Statements> getStatement();

} // Units
