/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.units;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.group32.units.units.UnitsFactory
 * @model kind="package"
 * @generated
 */
public interface UnitsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "units";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/group32/units/Units";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "units";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UnitsPackage eINSTANCE = uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.UnitsImpl <em>Units</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.UnitsImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getUnits()
   * @generated
   */
  int UNITS = 0;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNITS__STATEMENT = 0;

  /**
   * The number of structural features of the '<em>Units</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNITS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.StatementsImpl <em>Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.StatementsImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getStatements()
   * @generated
   */
  int STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.MassConversionImpl <em>Mass Conversion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.MassConversionImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getMassConversion()
   * @generated
   */
  int MASS_CONVERSION = 3;

  /**
   * The feature id for the '<em><b>Mass Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS_CONVERSION__MASS_VALUE = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Initial Mass Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS_CONVERSION__INITIAL_MASS_VALUE = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Converted Mass Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS_CONVERSION__CONVERTED_MASS_VALUE = STATEMENTS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Mass Conversion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS_CONVERSION_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.LengthConversionImpl <em>Length Conversion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.LengthConversionImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getLengthConversion()
   * @generated
   */
  int LENGTH_CONVERSION = 4;

  /**
   * The feature id for the '<em><b>Length Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_CONVERSION__LENGTH_VALUE = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Initial Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_CONVERSION__INITIAL_LENGTH = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Converted Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_CONVERSION__CONVERTED_LENGTH = STATEMENTS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Length Conversion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_CONVERSION_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.TimeConversionImpl <em>Time Conversion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.TimeConversionImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getTimeConversion()
   * @generated
   */
  int TIME_CONVERSION = 5;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CONVERSION__TIME = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Initial Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CONVERSION__INITIAL_TIME = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Converted Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CONVERSION__CONVERTED_TIME = STATEMENTS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Time Conversion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_CONVERSION_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.IntExpressionImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 6;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.IntLiteralImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 7;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.RealLiteralImpl <em>Real Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.RealLiteralImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getRealLiteral()
   * @generated
   */
  int REAL_LITERAL = 8;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__VAL = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Real Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.impl.IntVarExpressionImpl
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.MassUnits <em>Mass Units</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.MassUnits
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getMassUnits()
   * @generated
   */
  int MASS_UNITS = 10;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.TimeUnits <em>Time Units</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.TimeUnits
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getTimeUnits()
   * @generated
   */
  int TIME_UNITS = 11;

  /**
   * The meta object id for the '{@link uk.ac.kcl.group32.units.units.LengthUnits <em>Length Units</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.group32.units.units.LengthUnits
   * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getLengthUnits()
   * @generated
   */
  int LENGTH_UNITS = 12;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.Units <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Units</em>'.
   * @see uk.ac.kcl.group32.units.units.Units
   * @generated
   */
  EClass getUnits();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.group32.units.units.Units#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see uk.ac.kcl.group32.units.units.Units#getStatement()
   * @see #getUnits()
   * @generated
   */
  EReference getUnits_Statement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.Statements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statements</em>'.
   * @see uk.ac.kcl.group32.units.units.Statements
   * @generated
   */
  EClass getStatements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.group32.units.units.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.group32.units.units.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.group32.units.units.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.MassConversion <em>Mass Conversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mass Conversion</em>'.
   * @see uk.ac.kcl.group32.units.units.MassConversion
   * @generated
   */
  EClass getMassConversion();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.group32.units.units.MassConversion#getMassValue <em>Mass Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mass Value</em>'.
   * @see uk.ac.kcl.group32.units.units.MassConversion#getMassValue()
   * @see #getMassConversion()
   * @generated
   */
  EReference getMassConversion_MassValue();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.MassConversion#getInitialMassValue <em>Initial Mass Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Initial Mass Value</em>'.
   * @see uk.ac.kcl.group32.units.units.MassConversion#getInitialMassValue()
   * @see #getMassConversion()
   * @generated
   */
  EAttribute getMassConversion_InitialMassValue();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.MassConversion#getConvertedMassValue <em>Converted Mass Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Converted Mass Value</em>'.
   * @see uk.ac.kcl.group32.units.units.MassConversion#getConvertedMassValue()
   * @see #getMassConversion()
   * @generated
   */
  EAttribute getMassConversion_ConvertedMassValue();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.LengthConversion <em>Length Conversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Length Conversion</em>'.
   * @see uk.ac.kcl.group32.units.units.LengthConversion
   * @generated
   */
  EClass getLengthConversion();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.group32.units.units.LengthConversion#getLengthValue <em>Length Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Length Value</em>'.
   * @see uk.ac.kcl.group32.units.units.LengthConversion#getLengthValue()
   * @see #getLengthConversion()
   * @generated
   */
  EReference getLengthConversion_LengthValue();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.LengthConversion#getInitialLength <em>Initial Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Initial Length</em>'.
   * @see uk.ac.kcl.group32.units.units.LengthConversion#getInitialLength()
   * @see #getLengthConversion()
   * @generated
   */
  EAttribute getLengthConversion_InitialLength();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.LengthConversion#getConvertedLength <em>Converted Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Converted Length</em>'.
   * @see uk.ac.kcl.group32.units.units.LengthConversion#getConvertedLength()
   * @see #getLengthConversion()
   * @generated
   */
  EAttribute getLengthConversion_ConvertedLength();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.TimeConversion <em>Time Conversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Conversion</em>'.
   * @see uk.ac.kcl.group32.units.units.TimeConversion
   * @generated
   */
  EClass getTimeConversion();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.group32.units.units.TimeConversion#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see uk.ac.kcl.group32.units.units.TimeConversion#getTime()
   * @see #getTimeConversion()
   * @generated
   */
  EReference getTimeConversion_Time();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.TimeConversion#getInitialTime <em>Initial Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Initial Time</em>'.
   * @see uk.ac.kcl.group32.units.units.TimeConversion#getInitialTime()
   * @see #getTimeConversion()
   * @generated
   */
  EAttribute getTimeConversion_InitialTime();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.TimeConversion#getConvertedTime <em>Converted Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Converted Time</em>'.
   * @see uk.ac.kcl.group32.units.units.TimeConversion#getConvertedTime()
   * @see #getTimeConversion()
   * @generated
   */
  EAttribute getTimeConversion_ConvertedTime();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see uk.ac.kcl.group32.units.units.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see uk.ac.kcl.group32.units.units.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.group32.units.units.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Literal</em>'.
   * @see uk.ac.kcl.group32.units.units.RealLiteral
   * @generated
   */
  EClass getRealLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.group32.units.units.RealLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.group32.units.units.RealLiteral#getVal()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.group32.units.units.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see uk.ac.kcl.group32.units.units.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.group32.units.units.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.group32.units.units.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.group32.units.units.MassUnits <em>Mass Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Mass Units</em>'.
   * @see uk.ac.kcl.group32.units.units.MassUnits
   * @generated
   */
  EEnum getMassUnits();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.group32.units.units.TimeUnits <em>Time Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Units</em>'.
   * @see uk.ac.kcl.group32.units.units.TimeUnits
   * @generated
   */
  EEnum getTimeUnits();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.group32.units.units.LengthUnits <em>Length Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Length Units</em>'.
   * @see uk.ac.kcl.group32.units.units.LengthUnits
   * @generated
   */
  EEnum getLengthUnits();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UnitsFactory getUnitsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.UnitsImpl <em>Units</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.UnitsImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getUnits()
     * @generated
     */
    EClass UNITS = eINSTANCE.getUnits();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNITS__STATEMENT = eINSTANCE.getUnits_Statement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.StatementsImpl <em>Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.StatementsImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getStatements()
     * @generated
     */
    EClass STATEMENTS = eINSTANCE.getStatements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.MassConversionImpl <em>Mass Conversion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.MassConversionImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getMassConversion()
     * @generated
     */
    EClass MASS_CONVERSION = eINSTANCE.getMassConversion();

    /**
     * The meta object literal for the '<em><b>Mass Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MASS_CONVERSION__MASS_VALUE = eINSTANCE.getMassConversion_MassValue();

    /**
     * The meta object literal for the '<em><b>Initial Mass Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MASS_CONVERSION__INITIAL_MASS_VALUE = eINSTANCE.getMassConversion_InitialMassValue();

    /**
     * The meta object literal for the '<em><b>Converted Mass Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MASS_CONVERSION__CONVERTED_MASS_VALUE = eINSTANCE.getMassConversion_ConvertedMassValue();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.LengthConversionImpl <em>Length Conversion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.LengthConversionImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getLengthConversion()
     * @generated
     */
    EClass LENGTH_CONVERSION = eINSTANCE.getLengthConversion();

    /**
     * The meta object literal for the '<em><b>Length Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LENGTH_CONVERSION__LENGTH_VALUE = eINSTANCE.getLengthConversion_LengthValue();

    /**
     * The meta object literal for the '<em><b>Initial Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LENGTH_CONVERSION__INITIAL_LENGTH = eINSTANCE.getLengthConversion_InitialLength();

    /**
     * The meta object literal for the '<em><b>Converted Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LENGTH_CONVERSION__CONVERTED_LENGTH = eINSTANCE.getLengthConversion_ConvertedLength();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.TimeConversionImpl <em>Time Conversion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.TimeConversionImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getTimeConversion()
     * @generated
     */
    EClass TIME_CONVERSION = eINSTANCE.getTimeConversion();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIME_CONVERSION__TIME = eINSTANCE.getTimeConversion_Time();

    /**
     * The meta object literal for the '<em><b>Initial Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_CONVERSION__INITIAL_TIME = eINSTANCE.getTimeConversion_InitialTime();

    /**
     * The meta object literal for the '<em><b>Converted Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_CONVERSION__CONVERTED_TIME = eINSTANCE.getTimeConversion_ConvertedTime();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.IntExpressionImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.IntLiteralImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.RealLiteralImpl <em>Real Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.RealLiteralImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getRealLiteral()
     * @generated
     */
    EClass REAL_LITERAL = eINSTANCE.getRealLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__VAL = eINSTANCE.getRealLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.impl.IntVarExpressionImpl
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.MassUnits <em>Mass Units</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.MassUnits
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getMassUnits()
     * @generated
     */
    EEnum MASS_UNITS = eINSTANCE.getMassUnits();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.TimeUnits <em>Time Units</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.TimeUnits
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getTimeUnits()
     * @generated
     */
    EEnum TIME_UNITS = eINSTANCE.getTimeUnits();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.group32.units.units.LengthUnits <em>Length Units</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.group32.units.units.LengthUnits
     * @see uk.ac.kcl.group32.units.units.impl.UnitsPackageImpl#getLengthUnits()
     * @generated
     */
    EEnum LENGTH_UNITS = eINSTANCE.getLengthUnits();

  }

} //UnitsPackage
