/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.group32.units.UnitsRuntimeModule;
import uk.ac.kcl.group32.units.UnitsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UnitsIdeSetup extends UnitsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UnitsRuntimeModule(), new UnitsIdeModule()));
	}
	
}
