/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.ide;


/**
 * Use this class to register ide components.
 */
public class UnitsIdeModule extends AbstractUnitsIdeModule {
}
