/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UnitsUiModule extends AbstractUnitsUiModule {

	public UnitsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
