/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUnitsScopeProvider extends DelegatingScopeProvider {
}
