/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.units.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.group32.units.units.IntExpression;
import uk.ac.kcl.group32.units.units.LengthConversion;
import uk.ac.kcl.group32.units.units.LengthUnits;
import uk.ac.kcl.group32.units.units.UnitsPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Length Conversion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.group32.units.units.impl.LengthConversionImpl#getLengthValue <em>Length Value</em>}</li>
 *   <li>{@link uk.ac.kcl.group32.units.units.impl.LengthConversionImpl#getInitialLength <em>Initial Length</em>}</li>
 *   <li>{@link uk.ac.kcl.group32.units.units.impl.LengthConversionImpl#getConvertedLength <em>Converted Length</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LengthConversionImpl extends StatementsImpl implements LengthConversion
{
  /**
   * The cached value of the '{@link #getLengthValue() <em>Length Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLengthValue()
   * @generated
   * @ordered
   */
  protected IntExpression lengthValue;

  /**
   * The default value of the '{@link #getInitialLength() <em>Initial Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialLength()
   * @generated
   * @ordered
   */
  protected static final LengthUnits INITIAL_LENGTH_EDEFAULT = LengthUnits.KM;

  /**
   * The cached value of the '{@link #getInitialLength() <em>Initial Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialLength()
   * @generated
   * @ordered
   */
  protected LengthUnits initialLength = INITIAL_LENGTH_EDEFAULT;

  /**
   * The default value of the '{@link #getConvertedLength() <em>Converted Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConvertedLength()
   * @generated
   * @ordered
   */
  protected static final LengthUnits CONVERTED_LENGTH_EDEFAULT = LengthUnits.KM;

  /**
   * The cached value of the '{@link #getConvertedLength() <em>Converted Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConvertedLength()
   * @generated
   * @ordered
   */
  protected LengthUnits convertedLength = CONVERTED_LENGTH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LengthConversionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnitsPackage.Literals.LENGTH_CONVERSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntExpression getLengthValue()
  {
    return lengthValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLengthValue(IntExpression newLengthValue, NotificationChain msgs)
  {
    IntExpression oldLengthValue = lengthValue;
    lengthValue = newLengthValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE, oldLengthValue, newLengthValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLengthValue(IntExpression newLengthValue)
  {
    if (newLengthValue != lengthValue)
    {
      NotificationChain msgs = null;
      if (lengthValue != null)
        msgs = ((InternalEObject)lengthValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE, null, msgs);
      if (newLengthValue != null)
        msgs = ((InternalEObject)newLengthValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE, null, msgs);
      msgs = basicSetLengthValue(newLengthValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE, newLengthValue, newLengthValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LengthUnits getInitialLength()
  {
    return initialLength;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitialLength(LengthUnits newInitialLength)
  {
    LengthUnits oldInitialLength = initialLength;
    initialLength = newInitialLength == null ? INITIAL_LENGTH_EDEFAULT : newInitialLength;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnitsPackage.LENGTH_CONVERSION__INITIAL_LENGTH, oldInitialLength, initialLength));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LengthUnits getConvertedLength()
  {
    return convertedLength;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConvertedLength(LengthUnits newConvertedLength)
  {
    LengthUnits oldConvertedLength = convertedLength;
    convertedLength = newConvertedLength == null ? CONVERTED_LENGTH_EDEFAULT : newConvertedLength;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnitsPackage.LENGTH_CONVERSION__CONVERTED_LENGTH, oldConvertedLength, convertedLength));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE:
        return basicSetLengthValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE:
        return getLengthValue();
      case UnitsPackage.LENGTH_CONVERSION__INITIAL_LENGTH:
        return getInitialLength();
      case UnitsPackage.LENGTH_CONVERSION__CONVERTED_LENGTH:
        return getConvertedLength();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE:
        setLengthValue((IntExpression)newValue);
        return;
      case UnitsPackage.LENGTH_CONVERSION__INITIAL_LENGTH:
        setInitialLength((LengthUnits)newValue);
        return;
      case UnitsPackage.LENGTH_CONVERSION__CONVERTED_LENGTH:
        setConvertedLength((LengthUnits)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE:
        setLengthValue((IntExpression)null);
        return;
      case UnitsPackage.LENGTH_CONVERSION__INITIAL_LENGTH:
        setInitialLength(INITIAL_LENGTH_EDEFAULT);
        return;
      case UnitsPackage.LENGTH_CONVERSION__CONVERTED_LENGTH:
        setConvertedLength(CONVERTED_LENGTH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnitsPackage.LENGTH_CONVERSION__LENGTH_VALUE:
        return lengthValue != null;
      case UnitsPackage.LENGTH_CONVERSION__INITIAL_LENGTH:
        return initialLength != INITIAL_LENGTH_EDEFAULT;
      case UnitsPackage.LENGTH_CONVERSION__CONVERTED_LENGTH:
        return convertedLength != CONVERTED_LENGTH_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (initialLength: ");
    result.append(initialLength);
    result.append(", convertedLength: ");
    result.append(convertedLength);
    result.append(')');
    return result.toString();
  }

} //LengthConversionImpl
