/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.group32.units.ui.internal.UnitsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UnitsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(UnitsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		UnitsActivator activator = UnitsActivator.getInstance();
		return activator != null ? activator.getInjector(UnitsActivator.UK_AC_KCL_GROUP32_UNITS_UNITS) : null;
	}

}
