/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UnitsStandaloneSetup extends UnitsStandaloneSetupGenerated {

	public static void doSetup() {
		new UnitsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
