/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UnitsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/kcl/group32/units/parser/antlr/internal/InternalUnits.tokens");
	}
}
