/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.group32.units.parser.antlr.internal.InternalUnitsParser;
import uk.ac.kcl.group32.units.services.UnitsGrammarAccess;

public class UnitsParser extends AbstractAntlrParser {

	@Inject
	private UnitsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUnitsParser createParser(XtextTokenStream stream) {
		return new InternalUnitsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Units";
	}

	public UnitsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UnitsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
