/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.group32.units.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.group32.units.ui.internal.UnitsActivator;

public class UnitsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UnitsActivator.getInstance().getInjector("uk.ac.kcl.group32.units.Units");
	}

}
